"use client";

// PadelHub — quick "register member" modal used inside the New Booking flow.
// Minimal fields (nama, username, telepon, email) plus an optional membership
// plan, so front-desk can register a login-capable member on the spot without
// leaving the booking screen. The login password is generated by the system and
// shown after save. Persists to the tenant DB via registerMemberAction.

import React, { useEffect, useState } from "react";
import { ModalDialog } from "@/components/ui/modal";
import Button from "@/components/ui/button/Button";
import TextInput from "@/components/ui/input/TextInput";
import InputLabel from "@/components/ui/input/InputLabel";
import Badge from "@/components/ui/badge/Badge";
import PhoneInput, { type Country } from "@/components/ui/input/PhoneInput";
import { useToast } from "@/components/ui/toast/ToastContext";
import { formatIDR } from "@/components/club-core/format";
import countriesData from "@/data/countries.json";
import {
  registerMemberAction,
  getActivePlansAction,
  type PlanOption,
} from "@/app/(admin)/members/actions";

const countries = countriesData as Country[];

/** Lightweight member returned to the caller after a successful register. */
export interface CreatedMember {
  id: string;
  name: string;
  phone: string;
  tier: string;
}

interface QuickAddMemberModalProps {
  isOpen: boolean;
  onClose: () => void;
  /** prefilled name typed in the member search */
  initialName?: string;
  onCreated: (member: CreatedMember) => void;
}

const QuickAddMemberModal: React.FC<QuickAddMemberModalProps> = ({
  isOpen,
  onClose,
  initialName = "",
  onCreated,
}) => {
  const toast = useToast();
  const [name, setName] = useState(initialName);
  const [username, setUsername] = useState("");
  const [phone, setPhone] = useState("");
  const [email, setEmail] = useState("");
  const [submitted, setSubmitted] = useState(false);
  const [saving, setSaving] = useState(false);

  // membership plans (from DB) — optional selection at quick register
  const [plans, setPlans] = useState<PlanOption[]>([]);
  const [planId, setPlanId] = useState<string | null>(null);

  // suggest a username from the typed name
  const suggestUsername = (n: string) =>
    n.trim().toLowerCase().replace(/[^a-z0-9]+/g, "").slice(0, 20);

  // load active plans once the modal first opens
  useEffect(() => {
    if (!isOpen) return;
    let alive = true;
    (async () => {
      try {
        const rows = await getActivePlansAction();
        if (!alive) return;
        setPlans(rows);
        const def = rows.find((p) => p.highlighted) ?? rows[0] ?? null;
        setPlanId((cur) => cur ?? (def ? def.id : null));
      } catch {
        if (alive) setPlans([]);
      }
    })();
    return () => {
      alive = false;
    };
  }, [isOpen]);

  useEffect(() => {
    if (isOpen) {
      setName(initialName);
      setUsername(suggestUsername(initialName));
      setPhone("");
      setEmail("");
      setSubmitted(false);
      setSaving(false);
    }
  }, [isOpen, initialName]);

  const selectedPlan = plans.find((p) => p.id === planId) ?? null;

  const nameValid = name.trim().length >= 2;
  const usernameValid = username.trim().length >= 3;
  const phoneValid = phone.replace(/\D/g, "").length >= 8;
  const canSubmit = nameValid && usernameValid && phoneValid;

  const create = async () => {
    setSubmitted(true);
    if (!canSubmit || saving) return;
    setSaving(true);

    const res = await registerMemberAction({
      name: name.trim(),
      username: username.trim().toLowerCase(),
      phone,
      email: email.trim() || undefined,
      planId,
    });

    if (!res.success || !res.memberNo || !res.id) {
      toast.error(res.error || "Gagal mendaftarkan member.", "Registrasi gagal");
      setSaving(false);
      return;
    }

    toast.success(
      res.tempPassword
        ? `${name.trim()} terdaftar. Username: ${res.username} · Password: ${res.tempPassword}`
        : `${name.trim()} terdaftar (${res.memberNo}).`,
      "Member baru",
    );
    onCreated({
      id: res.id,
      name: name.trim(),
      phone,
      tier: selectedPlan ? selectedPlan.name.toLowerCase() : "daily",
    });
    onClose();
  };

  return (
    <ModalDialog
      isOpen={isOpen}
      onClose={onClose}
      title="Register Member Baru"
      description="Daftar cepat member (bisa login) + pilih membership untuk melanjutkan booking."
      size="md"
      footer={
        <div className="flex justify-end gap-2">
          <Button variant="outline" onClick={onClose} disabled={saving}>
            Batal
          </Button>
          <Button variant="primary" sheen onClick={create} disabled={saving}>
            {saving ? "Menyimpan…" : "Simpan & Pilih"}
          </Button>
        </div>
      }
    >
      <div className="space-y-5">
        <TextInput
          label="Nama Lengkap"
          labelInfo="Nama member yang tampil di booking, kalender & struk."
          value={name}
          onChange={(v) => {
            setName(v);
            if (!username || username === suggestUsername(name)) {
              setUsername(suggestUsername(v));
            }
          }}
          placeholder="cth. Andi Wijaya"
          required
          error={submitted && !nameValid}
          errorText="Nama minimal 2 karakter"
        />

        <TextInput
          label="Username"
          labelInfo="Username untuk login member. Huruf kecil tanpa spasi. Password dibuat otomatis oleh sistem."
          value={username}
          onChange={(v) => setUsername(v.toLowerCase().replace(/\s+/g, ""))}
          placeholder="cth. andiwijaya"
          required
          error={submitted && !usernameValid}
          errorText="Username minimal 3 karakter"
          hint="Password login dibuat otomatis & ditampilkan setelah simpan"
        />

        <PhoneInput
          label="Nomor Telepon"
          labelInfo="Nomor aktif untuk konfirmasi & notifikasi booking."
          required
          countries={countries}
          value={phone}
          onChange={(full) => setPhone(full)}
          error={submitted && !phoneValid}
          hint={
            submitted && !phoneValid
              ? "Nomor telepon belum valid"
              : "Format: +62 8xx xxxx xxxx"
          }
        />

        <TextInput
          label="Email (opsional)"
          labelInfo="Untuk notifikasi email. Boleh dikosongkan."
          type="email"
          value={email}
          onChange={setEmail}
          placeholder="cth. andi@email.com"
          validate
        />

        {/* Membership plan (optional) */}
        {plans.length > 0 && (
          <div>
            <InputLabel
              label="Membership (opsional)"
              tooltip="Plan menentukan join fee, kuota sesi 60 menit gratis, dan diskon. Pilih 'Tanpa plan' untuk member walk-in biasa."
            />
            <div className="grid grid-cols-1 gap-2.5 sm:grid-cols-2">
              {/* no-plan option */}
              <button
                type="button"
                onClick={() => setPlanId(null)}
                className={[
                  "rounded-xl border p-3 text-left transition-all",
                  planId === null
                    ? "border-[var(--color-primary)] bg-[var(--color-primary-light)] ring-2 ring-[var(--color-primary)]/30"
                    : "border-[var(--border-default)] bg-[var(--surface-card)] hover:border-[var(--color-primary)]/40",
                ].join(" ")}
              >
                <div className="flex items-center justify-between gap-2">
                  <span className="text-sm font-semibold text-[var(--text-heading)]">
                    Tanpa plan
                  </span>
                  <span className="text-xs font-medium text-[var(--text-caption)]">
                    Gratis
                  </span>
                </div>
                <p className="mt-1 text-xs text-[var(--text-caption)]">
                  Walk-in, bayar penuh per booking.
                </p>
              </button>

              {plans.map((p) => {
                const active = p.id === planId;
                return (
                  <button
                    key={p.id}
                    type="button"
                    onClick={() => setPlanId(p.id)}
                    className={[
                      "rounded-xl border p-3 text-left transition-all",
                      active
                        ? "border-[var(--color-primary)] bg-[var(--color-primary-light)] ring-2 ring-[var(--color-primary)]/30"
                        : "border-[var(--border-default)] bg-[var(--surface-card)] hover:border-[var(--color-primary)]/40",
                    ].join(" ")}
                  >
                    <div className="flex items-center justify-between gap-2">
                      <span
                        className="rounded-full px-2 py-0.5 text-xs font-semibold text-white"
                        style={{ background: p.color }}
                      >
                        {p.name}
                      </span>
                      <span className="text-xs font-bold text-[var(--text-heading)]">
                        {p.joinFee === 0 ? "Gratis" : formatIDR(p.joinFee)}
                      </span>
                    </div>
                    <div className="mt-1.5 flex flex-wrap gap-1">
                      {p.includedCourtBookings > 0 && (
                        <Badge size="sm" color="info" variant="light">
                          {p.includedCourtBookings} sesi gratis
                        </Badge>
                      )}
                      {p.courtDiscountPct > 0 && (
                        <Badge size="sm" color="success" variant="light">
                          {p.courtDiscountPct}% off
                        </Badge>
                      )}
                    </div>
                  </button>
                );
              })}
            </div>
            {selectedPlan && selectedPlan.joinFee > 0 && (
              <p className="mt-2 text-xs text-[var(--text-caption)]">
                Join fee {formatIDR(selectedPlan.joinFee)} ditagih saat pembayaran.
              </p>
            )}
          </div>
        )}
      </div>
    </ModalDialog>
  );
};

export default QuickAddMemberModal;
